dasch-swiss/dsp-ingest

- build.sbt
Disable the coverage in the `build.sbt`. For some reason if this flag is set to true the coverage is added to the docker container and prevents the container from properly starting up:
```
2023-06-30 17:34:05 Exception in thread "main" java.lang.ExceptionInInitializerError
2023-06-30 17:34:05 at swiss.dasch.Main$.<clinit>(Main.scala:22)
2023-06-30 17:34:05 at swiss.dasch.Main.main(Main.scala)
2023-06-30 17:34:05 Caused by: java.io.FileNotFoundException: /Users/mpro/repos/dsp-ingest/target/scala-3.3.0/scoverage-data/scoverage.measurements.a0c18b7e-a94f-4b04-babb-91c7abceb6cc.1 (No such file or directory)
2023-06-30 17:34:05 at java.base/java.io.FileOutputStream.open0(Native Method)
2023-06-30 17:34:05 at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
2023-06-30 17:34:05 …
```
> disable coverage in build.sbt

- src/main/scala/swiss/dasch/infrastructure/IngestApiServer.scala
When uploading an import zip the `Server` rejected it with a 413 response: `Request Entity Too Large`
Enabling streaming the reqest prevents this error.
> fix: Enable request streaming

- src/main/scala/swiss/dasch/Main.scala
- src/main/scala/swiss/dasch/api/monitoring/HealthCheckService.scala
- src/main/scala/swiss/dasch/infrastructure/FileSystemCheck.scala
- src/test/scala/swiss/dasch/infrastructure/FileSystemCheckLiveSpec.scala
* fail starting up if asset and temp directories do not exist
* create folders in temp dir if they do not exist
> chore: Add FilesystemCheck on startup

- .github/workflows/ci.yml
- src/main/scala/swiss/dasch/domain/Asset.scala
- src/test/scala/swiss/dasch/domain/AssetIdSpec.scala
While running the topleft correction maintenance action on test I discovered that some assets in the 0803 project have names like `incunabula_0000004791.jp2` containing an underscore.
Fix the `AssetId` model to allow for underscores in the `AssetId` model.
> fix: Allow underscore in AssetIds

- src/main/scala/swiss/dasch/domain/MaintenanceActions.scala
For some reason Sipi cannot transcode a valid jpx file and does so without logging an error. Sipi simply finishes without any output.
In order to complete the create originals for the other files we have to skip the file and log a warning and recreate those manually.
> fix: Skip images which Sipi fails to transcode while creating originals

- src/main/scala/swiss/dasch/Main.scala
- src/main/scala/swiss/dasch/api/IngestEndpoint.scala
- src/main/scala/swiss/dasch/domain/AssetId.scala
- src/main/scala/swiss/dasch/domain/AssetInfoService.scala
- src/main/scala/swiss/dasch/domain/SipiClient.scala
- src/main/scala/swiss/dasch/infrastructure/Base62.scala
- src/main/scala/swiss/dasch/infrastructure/IngestApiServer.scala
- src/test/scala/swiss/dasch/domain/AssetIdSpec.scala
- src/test/scala/swiss/dasch/infrastructure/Base62Spec.scala
Adds a bulk ingest endpoint:
```
POST /projects/<shortcode>/bulk-ingest HTTP/1.1
Authorization: Bearer <token>
Host: localhost:3340
```
Only ingests images by traversing the `tmp/import/<shortcode>` folder and for each image it:
* creates `.orig`
* creates derivative `.jpx`, should Sipi fail to transcode this image logs an error and skips the following steps
* creates `.info` with checksums and original filename
* creates a `mapping.csv` which contains `originalFilename, internalFilename` mapping
* removes the image from the temp folder.
> feat: Add bulk ingest for images

- src/main/scala/swiss/dasch/api/IngestEndpoint.scala
- src/main/scala/swiss/dasch/domain/StorageService.scala
- src/test/scala/swiss/dasch/domain/StorageServiceLiveSpec.scala
Should a file exist in a subfolder with the same name as another file we have to be able to distinguish these files in the mapping.csv. Include the folder path inside the import/<project_shortcode> as part of the original in the mapping.csv resolves this ambiguity.
The new content of the `mapping-<project_shortcode>.csv` file  would look like this:
```
original,derivative
100x100.png,75JdC5Idk6o-QjUEZWoAT3r.jpx
subfolder/100x100.png,1Ty6tYGtiMw-fxm9fbsvCV7.jpx
subfolder/subfolder2/100x100.png,3sILHLNzSfw-rbWPMoGmwEC.jpx
...
```
for an import folder like:
```
import/<project_shortcode>/
├── 100x100.png
│ 
└── subfolder/
├── 100x100.png
│
└── subfolder2/
└── 100x100.png
```
> fix: Include folder name in mapping.csv in order to prevent collisions

- .scala-steward.conf
PRs are created only again after the seven days since the last PR.
Scala Steward should group should group updates in order to reduce the number of pull-requests. Three groups: patch version updates, minor/major version updated, everything else.
Start every commit message with `chore: ` in order to comply with our rules.
> chore: Add Scala Steward configuration

- .github/workflows/ci.yml
Build and test project with Java 21 in parallel with Java 17.
Currently temurin [is publishing  their Java 21 for production use](https://github.com/adoptium/temurin/issues/8).
_Out of scope_
Use of Java 21 in published Docker artefact, this is still on Java 17.
> chore: Add Java 21 to build and test DEV-2769

- .github/workflows/check-pr-title.yml
- .github/workflows/release-please.yaml
- .scala-steward.conf
Update release please and scala steward PR titles.
Forcing an initial upper case letter will let the release please generated release notes look more consistent than with mixed case titles.
> chore: Force PR titles to start with an upper case letter

- .scala-steward.conf
- build.sbt
This PR:
- improves dependency grouping to as it is now in dsp-ap,
- changes the frequency of updates, from every 7 days, to twice per week (defined in `scala-steward.yml` file),
- cleans up `build.sbt` file.
> chore(scala-steward): Improve dependency grouping 

- src/main/scala/swiss/dasch/domain/BulkIngestService.scala
- src/main/scala/swiss/dasch/domain/StorageService.scala
Actually a non-issue which should not occur unless the image files to be ingested are in the wrong place. But I only found this out after I did the work and it still improves the code, so I'd merge it anyways, if that's ok.
> fix: Ingest fails when mapping file folder does not exist (DEV-3055)

- src/main/scala/swiss/dasch/Main.scala
- src/main/scala/swiss/dasch/domain/AssetModel.scala
- src/main/scala/swiss/dasch/domain/BulkIngestService.scala
- src/main/scala/swiss/dasch/domain/IngestService.scala
- src/main/scala/swiss/dasch/domain/StorageService.scala
- src/main/scala/swiss/dasch/domain/SupportedFileType.scala
- src/test/scala/swiss/dasch/api/ProjectsEndpointSpec.scala
- src/test/scala/swiss/dasch/domain/IngestServiceSpec.scala
- src/test/scala/swiss/dasch/domain/StorageServiceLiveSpec.scala
Extract code for ingesting a single file to `IngestService` and add a simple test.
Move code for `StorageService` methods `getBulkIngestImportFolder` and `createBulkIngestMappingFile` into the `BulkIngestService`.
> refactor: Extract IngestService

- src/main/scala/swiss/dasch/api/ProjectsEndpoints.scala
- src/main/scala/swiss/dasch/api/ProjectsEndpointsHandler.scala
- src/main/scala/swiss/dasch/domain/BulkIngestService.scala
- src/main/scala/swiss/dasch/domain/StorageService.scala
- src/test/scala/swiss/dasch/domain/BulkIngestServiceLiveSpec.scala
`GET /projects/<shortcode>/bulk-ingest/mapping.csv` endpoint
Returns the current state of the mapping csv. May be incomplete if a bulk-ingest is still in progress.
`POST /projects/<shortcode>/bulk-ingest/finalize` endpoint
Removes the `/tmp/<shortcode>` and `/tmp/mapping-<shortcode>.csv` files and folders.
> feat: Add get mapping.csv and finalize endpoints

- src/main/scala/swiss/dasch/api/HandlerFunctions.scala
- src/main/scala/swiss/dasch/api/ProjectsEndpoints.scala
- src/main/scala/swiss/dasch/api/ProjectsEndpointsHandler.scala
- src/main/scala/swiss/dasch/domain/AssetInfoService.scala
- src/main/scala/swiss/dasch/domain/AssetMetadata.scala
- src/main/scala/swiss/dasch/domain/AssetModel.scala
- src/main/scala/swiss/dasch/domain/FileChecksumService.scala
- src/main/scala/swiss/dasch/domain/IngestService.scala
- src/main/scala/swiss/dasch/domain/MaintenanceActions.scala
- src/main/scala/swiss/dasch/domain/MovingImageService.scala
- src/main/scala/swiss/dasch/domain/StillImageService.scala
- src/main/scala/swiss/dasch/domain/StorageService.scala
- src/test/scala/swiss/dasch/api/MaintenanceEndpointsSpec.scala
- src/test/scala/swiss/dasch/domain/AssetIdSpec.scala
- src/test/scala/swiss/dasch/domain/AssetInfoServiceSpec.scala
- src/test/scala/swiss/dasch/domain/FileChecksumServiceLiveSpec.scala
- src/test/scala/swiss/dasch/domain/ImageServiceLiveSpec.scala
- src/test/scala/swiss/dasch/domain/IngestServiceSpec.scala
- src/test/scala/swiss/dasch/domain/MovingImageServiceSpec.scala
- src/test/scala/swiss/dasch/domain/StorageServiceLiveSpec.scala
- src/test/scala/swiss/dasch/test/SpecConstants.scala
This endpoint returns the asset's `.info` file contents as json.
`GET /projects/<shortcode>/assets/<assetId>/info endpoint`
Sample Response:
```json
{
"internalFilename": "5IrpYt6Y0j3-FNPJ47uoyw7.jpx",
"originalInternalFilename": "5IrpYt6Y0j3-FNPJ47uoyw7.jpg.orig",
"originalFilename": "ir14_ny_m_pfi_10_11_moh-v.jpg",
"checksumOriginal": "db5e971f4464e93d3cb04257f819e79626176a1db7b153557ffc6cc95bb06cd0",
"checksumDerivative": "0b1f3b573d10c544334eee714e1887ded617ed10b1a57940f1afc68abfe943a2"
}
```
Extend the `.info` for image files to contain the `width` and `height`, get this information during an ingest.
_Out of scope_
Add a maintenance action which adds image metadata to the `.info` file for all existing assets.
> feat: Add asset info endpoint and image meta data extraction

- build.sbt
- src/main/scala/swiss/dasch/infrastructure/CommandExecutorLive.scala
- src/test/scala/swiss/dasch/infrastructure/CommandExecutorLiveSpec.scala
We have to use a stable version for the `daschswiss/knora-sipi` container because `dsp-api` publishes unstable versions on each commit on main. Hence the `latest` tag is unsuitable.
> fix: Use a stable version for Sipi base image

- build.sbt
Update knora-sipi to v30.8.2 including sipi version 3.8.12
> fix(sipi): Fix creating a valid JPX from grey scale JPEG (DEV-3259)

- src/main/scala/swiss/dasch/domain/MovingImageService.scala
During the migration to safer commandline execution the command for ffprobe was not updated.
This fixes ingesting moving images.
> fix: Fix extracting moving image metadata

- src/main/scala/swiss/dasch/Endpoints.scala
- src/main/scala/swiss/dasch/Main.scala
- src/main/scala/swiss/dasch/api/ProjectsEndpoints.scala
- src/main/scala/swiss/dasch/api/ReportEndpoints.scala
- src/main/scala/swiss/dasch/api/ReportEndpointsHandler.scala
- src/main/scala/swiss/dasch/domain/ReportService.scala
- src/main/scala/swiss/dasch/domain/StorageService.scala
- src/main/scala/swiss/dasch/domain/SupportedFileType.scala
- src/test/scala/swiss/dasch/api/ProjectsEndpointSpec.scala
Adds endpoint to trigger the asynchronous creation of the report in `tmp/reports/asset-overview_YYY-MM-DDTHH:MM:SS.NNNNNZ.json`
```http
POST http://0.0.0.0:3340/report/asset-overview
Authorization: Bearer foo
```
Produces a report like this:
```json
[
{
"shortcode" : "0001",
"totalNrOfAssets" : 5,
"nrOfAssetsPerType" : {
"StillImage" : 5
},
"sizesPerType" : {
"sizes" : {
"StillImage" : {
"SizeInBytesOther" : {
"fileType" : {
"StillImage" : {}
},
"sizeOrig" : "54,48 KiB",
"sizeDerivative" : "14,91 KiB"
}
}
}
}
},
{
"shortcode" : "0002",
"totalNrOfAssets" : 4,
"nrOfAssetsPerType" : {
"MovingImage" : 1,
"StillImage" : 2,
"OtherFiles" : 1
},
"sizesPerType" : {
"sizes" : {
"MovingImage" : {
"SizeInBytesMovingImages" : {
"sizeOrig" : "30,03 MiB",
"sizeDerivative" : "30,03 MiB",
"sizeKeyframes" …
```
> feat: Add assets overview report

- .github/workflows/release-please.yaml
To prevent release PRs be in "ready for review" state during entire release cycle.
> chore: Start release PRs as draft

- build.sbt
Failing build on main branch:
https://github.com/dasch-swiss/dsp-ingest/actions/runs/8519129341/job/23332595535
Locally I was able to determine that the first `apt install` already fails, needs an `apt update` first.
> chore: Fix failing docker build while installing dependencies because of missing 'apt-update'

- docs/api-authentication.md
- src/main/scala/swiss/dasch/api/MaintenanceEndpoints.scala
- src/main/scala/swiss/dasch/api/ProjectsEndpoints.scala
1. The endpoint descriptions look roughly like this:
<kbd><img width="379" alt="Screenshot 2024-04-22 at 16 01 19" src="https://github.com/dasch-swiss/dsp-ingest/assets/235147/8357fa2e-c3ca-4953-ac81-1fbde653bd45"></kbd>
I tried to make common code to append the descriptions, but it wasn't so easy and I didn't want to delve into the tapir implementation details to match the right type to add the implicits.
2. The authorization markdown page update looks like this:
<kbd><img width="803" alt="Screenshot 2024-04-22 at 15 28 20" src="https://github.com/dasch-swiss/dsp-ingest/assets/235147/fe1ea93b-182a-4c73-a012-2ee738152a4b"></kbd>
> docs: Add docs for endpoint authorization (DEV-3452)

- src/main/scala/swiss/dasch/api/ProjectsEndpointsHandler.scala
- src/main/scala/swiss/dasch/domain/ProjectService.scala
- src/main/scala/swiss/dasch/domain/StorageService.scala
When ingesting files to a non-existing project the ingest fails because of the project folder not existing.
Create the project folder in this case.
> fix: Create the project folder if it does not exist yet when ingesting individual assets (DEV-3620)

- src/main/scala/swiss/dasch/domain/BulkIngestService.scala
- src/main/scala/swiss/dasch/domain/IngestService.scala
- src/test/scala/swiss/dasch/domain/BulkIngestServiceSpec.scala
The problem lied in an omited `.some` in the `acquireWithTimeout`. Tests for `startBulkIngest` aded also.
> fix: Fix BulkIngestService locking for forked fibers (DEV-3769)

- src/main/scala/swiss/dasch/domain/AssetFilename.scala
- src/test/scala/swiss/dasch/api/ProjectsEndpointSpec.scala
Frontend should not be sending them in the first place, but ok.
FYI: denormalized means ā = a + ¯ in the unicode sequence instead of the specialized, combined character https://www.compart.com/en/unicode/U+0101.
> fix: Handle denormalized filenames in asset upload (DEV-3974)

- src/main/scala/swiss/dasch/domain/AssetFilename.scala
- src/test/scala/swiss/dasch/api/ProjectsEndpointSpec.scala
… (#254)"
This reverts commit 99b57dba31ff85d564cf7d4068a4c08855296041.
> fix: Revert 99b57dba3 "Handle denormalized filenames in asset upload (DEV-3974) (#254)"

- src/main/scala/swiss/dasch/domain/AssetFilename.scala
- src/main/scala/swiss/dasch/domain/ProjectService.scala
- src/test/scala/swiss/dasch/api/ProjectsEndpointSpec.scala
Seems like this should work, it does locally. Assuming the problem was not with the fix (see the unreverted commit), but with the directories.
When the directory wasn't present, it tried to insert the record in the db, which failed due to unique constraints. Though I still have not found the explanation for the case where the project ID is made up. Maybe the project data missing somewhere else triggers this.
> fix: Always create dirs, use db as primary info source (DEV-3974) + unrevert

- src/main/scala/swiss/dasch/domain/AssetFilename.scala
- src/test/scala/swiss/dasch/domain/AssetFilenameSpec.scala
* Allow `+=?!<>|`
* Add more tests for letters of other alphabets
add more tests
> feat: Allow more characters for asset file names (DEV-4082)

- build.sbt
This reverts the upgrade of the sttp client in commit 073947c7014f8c5f0e00992d7e9635292fa4c0ee.
The ugrade prevented the application to startup. It failed with an error:
```
java.lang.Error: Defect in zio.ZEnvironment: HashSet(SttpBackend[=λ %0 → ZIO[-Any,+Throwable,+0],+{package::WebSockets & ZioStreams}]) statically known to be contained within the environment are missing
```
I have created a bug report https://github.com/softwaremill/sttp/issues/2317
> chore: Revert Minor dependency updates (#279)

- src/main/scala/swiss/dasch/api/ProjectsEndpoints.scala
- src/main/scala/swiss/dasch/api/ProjectsEndpointsHandler.scala
Content-Disposition header was malformed for the UTF-8 case, though firefox understood it.
> fix: Fix Content-Disposition, allow CORS for original downloads (DEV-4371)

- src/main/scala/swiss/dasch/domain/AssetFilename.scala
- src/test/scala/swiss/dasch/domain/AssetFilenameSpec.scala
- add []{} special characters and improve test
- remove not allowed ? character
- add test for not allowed ? and / characters
> fix: Fix filename regex

- .github/workflows/ci.yml
ARM builds have recently stopped working due to https://github.com/docker/setup-qemu-action/issues/198
Our errors
```
[error] 44.35 Setting up libc-bin (2.35-0ubuntu3.9) ...
[error] 44.48 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[error] 44.84 Segmentation fault (core dumped)
```
match with what's described in https://github.com/docker/setup-qemu-action/issues/199
The temporary workaround seems to be pinning qemu to an older version.
> chore(ci): Temporary workaround for ARM builds

- src/main/scala/swiss/dasch/infrastructure/CommandExecutorLive.scala
- src/test/scala/swiss/dasch/infrastructure/CommandExecutorLiveSpec.scala
Since this is the main entrypoint for images entering into our repository, errors might prove beneficial for cases when formatting fails, especially now that error reporting has been improved by replacing syslog calls with just prints.
> feat: Forward Sipi logs (DEV-4518)

- docs/index.md
- src/main/scala/swiss/dasch/domain/SupportedFileType.scala
- src/test/scala/swiss/dasch/domain/SupportedFileTypeSpec.scala
- **add mimetypes: https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/MIME_types/Common_types**
- **feat: Add support for HTML and epub file types**
Updated the api documentation in https://github.com/dasch-swiss/dsp-api/pull/3649
> feat: Add support for HTML and epub file types (DEV-5080)
